describe('template spec', () => {
  it('passes', () => {
    cy.visit('/')
    cy.findByRole("link", { name: "Line"}).click()
    cy.url().should("contain", "line")
    cy.findByLabelText("Chart title").type("cats v dogs")
    cy.findByLabelText("X label").type("cats")
    cy.findByLabelText("Y label").type("dogs")
    cy.findByRole("button", { name: "+"}).click()
    cy.findByRole("button", { name: "+"}).click()
    cy.findByTestId("data-1").type('1')
    cy.findByTestId("data-2").type('3')
    cy.findByTestId("data-3").type('2')
    cy.findByTestId("data-4").type('7')
    cy.findByTestId("data-5").type('3')
    cy.findByTestId("data-6").type('15')
    cy.findByRole("button", { name: "Generate chart"}).click()
    cy.findByRole("img").should('exist')
  })
})